# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-demo',
                'doc_host': 'https://MehmetSavas.github.io',
                'git_url': 'https://github.com/MehmetSavas/nbdev-demo',
                'lib_path': 'nbdev_demo'},
  'syms': { 'nbdev_demo.data_handler': { 'nbdev_demo.data_handler.convert_to_float': ( 'data_handler.html#convert_to_float',
                                                                                       'nbdev_demo/data_handler.py'),
                                         'nbdev_demo.data_handler.some_api_call': ( 'data_handler.html#some_api_call',
                                                                                    'nbdev_demo/data_handler.py'),
                                         'nbdev_demo.data_handler.transform_data': ( 'data_handler.html#transform_data',
                                                                                     'nbdev_demo/data_handler.py')},
            'nbdev_demo.main_strategy': { 'nbdev_demo.main_strategy.predict_prices': ( 'main_strategy.html#predict_prices',
                                                                                       'nbdev_demo/main_strategy.py')}}}
